#page title
page_title                                : LinkVault

# App Info
ios_app_id                                : 1592234033 
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : assets/presskit.zip  
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/linkvault.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your All-in-One Mobile Link Organizer!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :
your_link                                 : https://apps.apple.com/us/app/linkvault/id1592234033
your_city                                 : 
email_address                             : linkvault.app@gmail.com
facebook_username                         : linkvaultapp                              
instagram_username                        : linkvault 
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Privacy-focused
    description                           : Your data is saved locally and backed up in your iCloud storage.
    fontawesome_icon_name                 : cloud
    
  - title                                 : Easy link management 
    description                           : Add links by pasting the URL, scanning a QR code, sharing directly from other apps, or using the iOS widget.
    fontawesome_icon_name                 : gear

  - title                                 : Customization
    description                           : Add notes and tags to each saved link for easy organization and categorization.
    fontawesome_icon_name                 : link 

  - title                                 : Efficient Search 
    description                           : Quickly find links with the built-in search function and group them by tags.
    fontawesome_icon_name                 : magnifying-glass

  - title                                 : Export 
    description                           : Easily export your links for backup or sharing.
    fontawesome_icon_name                 : file-export
  

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
